export const PLAYERS = [
  "Adam",
  "Alex",
  "Ben",
  "Connor",
  "Kylee",
  "Nick",
  "Noah",
  "Rick",
  "Ricky",
  "Tammy",
];

export const RICK_TO_ESPN = [
  ["ATL", "ATL"],
  ["AZ", "ARI"],
  ["BALT", "BAL"],
  ["BUF", "BUF"],
  ["CAR", "CAR"],
  ["CHIC", "CHI"],
  ["CLEV", "CLE"],
  ["CN", "CIN"],
  ["DAL", "DAL"],
  ["DEN", "DEN"],
  ["DET", "DET"],
  ["GB", "GB"],
  ["GIA", "NYG"],
  ["HOU", "HOU"],
  ["INDY", "IND"],
  ["JAX", "JAX"],
  ["JETS", "NYJ"],
  ["KC", "KC"],
  ["LAC", "LAC"],
  ["LAR", "LAR"],
  ["LV", "LV"],
  ["MIA", "MIA"],
  ["MN", "MIN"],
  ["NE", "NE"],
  ["NO", "NO"],
  ["PITT", "PIT"],
  ["PHIL", "PHI"],
  ["SEAT", "SEA"],
  ["SF", "SF"],
  ["TB", "TB"],
  ["TN", "TEN"],
  ["WASH", "WSH"],
];

export const ESPN_TO_RICK = [
  ["ATL", "ATL"],
  ["ARI", "AZ"],
  ["BAL", "BALT"],
  ["BUF", "BUF"],
  ["CAR", "CAR"],
  ["CHI", "CHIC"],
  ["CLE", "CLEV"],
  ["CIN", "CN"],
  ["DAL", "DAL"],
  ["DEN", "DEN"],
  ["DET", "DET"],
  ["GB", "GB"],
  ["NYG", "GIA"],
  ["HOU", "HOU"],
  ["IND", "INDY"],
  ["JAX", "JAX"],
  ["NYJ", "JETS"],
  ["KC", "KC"],
  ["LAC", "LAC"],
  ["LAR", "LAR"],
  ["LV", "LV"],
  ["MIA", "MIA"],
  ["MIN", "MN"],
  ["NE", "NE"],
  ["NO", "NO"],
  ["PIT", "PITT"],
  ["PHI", "PHIL"],
  ["SEA", "SEAT"],
  ["SF", "SF"],
  ["TB", "TB"],
  ["TEN", "TN"],
  ["WSH", "WASH"],
];
